spring:
  profiles:
    include:
      - fcm
  data:
    redis:
      port: 6379
      host: localhost


# multipartFile 용량 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB