spring:
  profiles:
    include:
      - fcm
  data:
    redis:
      port: 6379
      host: localhost


# multipartFile 용량 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: AKIARS33SSNQQ4PT5SX6
      secretKey: 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
    s3:
      bucket: plowithmebucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
